import { describe, it, expect, vi } from 'vitest'

describe('env validation', () => {
  it('throws when NEXT_PUBLIC_SUPABASE_URL is missing', async () => {
    vi.resetModules()
    vi.stubEnv('NEXT_PUBLIC_SUPABASE_URL', '')
    vi.stubEnv('NEXT_PUBLIC_SUPABASE_ANON_KEY', 'anon')
    vi.stubEnv('SUPABASE_SERVICE_ROLE_KEY', 'service')
    vi.stubEnv('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY', 'pk_test')
    vi.stubEnv('CLERK_SECRET_KEY', 'sk_test')
    vi.stubEnv('ANTHROPIC_API_KEY', 'sk-ant')
    vi.stubEnv('RESEND_API_KEY', 're_test')
    vi.stubEnv('RESEND_FROM_EMAIL', 'test@test.com')
    vi.stubEnv('RESEND_ALERT_EMAIL', 'alert@test.com')
    vi.stubEnv('BLOB_READ_WRITE_TOKEN', 'blob_test')
    await expect(import('@/lib/env')).rejects.toThrow()
    vi.unstubAllEnvs()
  })

  it('exports all required keys when env is valid', async () => {
    vi.resetModules()
    vi.stubEnv('NEXT_PUBLIC_SUPABASE_URL', 'https://test.supabase.co')
    vi.stubEnv('NEXT_PUBLIC_SUPABASE_ANON_KEY', 'anon')
    vi.stubEnv('SUPABASE_SERVICE_ROLE_KEY', 'service')
    vi.stubEnv('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY', 'pk_test')
    vi.stubEnv('CLERK_SECRET_KEY', 'sk_test')
    vi.stubEnv('ANTHROPIC_API_KEY', 'sk-ant')
    vi.stubEnv('RESEND_API_KEY', 're_test')
    vi.stubEnv('RESEND_FROM_EMAIL', 'test@test.com')
    vi.stubEnv('RESEND_ALERT_EMAIL', 'alert@test.com')
    vi.stubEnv('BLOB_READ_WRITE_TOKEN', 'blob_test')
    const { env } = await import('@/lib/env')
    expect(env.NEXT_PUBLIC_SUPABASE_URL).toBe('https://test.supabase.co')
    expect(env.NEXT_PUBLIC_SUPABASE_ANON_KEY).toBe('anon')
    expect(env.SUPABASE_SERVICE_ROLE_KEY).toBe('service')
    expect(env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY).toBe('pk_test')
    expect(env.CLERK_SECRET_KEY).toBe('sk_test')
    expect(env.ANTHROPIC_API_KEY).toBe('sk-ant')
    expect(env.RESEND_API_KEY).toBe('re_test')
    expect(env.RESEND_FROM_EMAIL).toBe('test@test.com')
    expect(env.RESEND_ALERT_EMAIL).toBe('alert@test.com')
    expect(env.BLOB_READ_WRITE_TOKEN).toBe('blob_test')
    vi.unstubAllEnvs()
  })
})
