// Placeholder types — generated by `npx supabase gen types typescript --local`.
// Local Supabase was unavailable (Docker not running), so this is a minimal hand-written
// placeholder so the client utilities compile. Regenerate with the command above as the
// schema evolves. Do not hand-edit otherwise.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      grants: {
        Row: {
          id: string
          title: string
          source: string
          description: string | null
          funder_name: string | null
          award_min: number | null
          award_max: number | null
          deadline: string | null
          status: string
          requires_loi: boolean
          requires_video: boolean
          is_new_program: boolean
          content_hash: string | null
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['grants']['Row']>
        Update: Partial<Database['public']['Tables']['grants']['Row']>
      }
      business_entities: {
        Row: {
          id: string
          name: string
          type: string
          mission: string | null
          is_african_american_owned: boolean
          is_minority_owned: boolean
          is_tech_company: boolean
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['business_entities']['Row']>
        Update: Partial<Database['public']['Tables']['business_entities']['Row']>
      }
      grant_matches: {
        Row: {
          id: string
          grant_id: string
          entity_id: string
          fit_score: number | null
          status: string
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['grant_matches']['Row']>
        Update: Partial<Database['public']['Tables']['grant_matches']['Row']>
      }
      grant_applications: {
        Row: {
          id: string
          grant_id: string
          entity_id: string
          status: string
          qa_passed: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['grant_applications']['Row']>
        Update: Partial<Database['public']['Tables']['grant_applications']['Row']>
      }
      loi_submissions: {
        Row: {
          id: string
          grant_id: string
          entity_id: string | null
          status: string
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['loi_submissions']['Row']>
        Update: Partial<Database['public']['Tables']['loi_submissions']['Row']>
      }
      notifications: {
        Row: {
          id: string
          type: string
          title: string
          body: string | null
          read: boolean
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['notifications']['Row']>
        Update: Partial<Database['public']['Tables']['notifications']['Row']>
      }
      scraper_runs: {
        Row: {
          id: string
          source: string
          success: boolean | null
          grants_found: number
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['scraper_runs']['Row']>
        Update: Partial<Database['public']['Tables']['scraper_runs']['Row']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      funder_type: 'federal' | 'state' | 'foundation' | 'corporate' | 'niche'
      grant_status: 'active' | 'expired' | 'archived'
      match_status:
        | 'queued'
        | 'drafting'
        | 'qa_review'
        | 'pending_review'
        | 'approved'
        | 'submitted'
        | 'rejected'
        | 'archived'
      application_status:
        | 'drafting'
        | 'qa_failed'
        | 'pending_review'
        | 'approved'
        | 'submitted'
        | 'rejected'
        | 'withdrawn'
      loi_status: 'draft' | 'submitted' | 'accepted' | 'rejected'
    }
  }
}
